# --- TYPE CONSTANTS ---

# Object type constants
OBJECT_TYPE_TRAP = 0
OBJECT_TYPE_STATUE = 1
OBJECT_TYPE_FOUNTAIN = 2
OBJECT_TYPE_STAIRS_UP = 3
OBJECT_TYPE_STAIRS_DOWN = 4
OBJECT_TYPE_RUBBLE = 5
OBJECT_TYPE_PILLAR = 6
OBJECT_TYPE_ALTAR = 7
OBJECT_TYPE_THRONE = 8
OBJECT_TYPE_CHEST = 9
OBJECT_TYPE_LEVER = 10
OBJECT_TYPE_BUTTON = 11
OBJECT_TYPE_CHAIR = 12
OBJECT_TYPE_DEAD_BODY = 13
OBJECT_TYPE_TABLE = 14
OBJECT_TYPE_BED = 15
OBJECT_TYPE_POOL = 16

# Item type constants
ITEM_TYPE_POTION = 0
ITEM_TYPE_SCROLL = 1
ITEM_TYPE_WEAPON = 2
ITEM_TYPE_ARMOR = 3
ITEM_TYPE_GOLD = 4

# Encounter type constants
ENCOUNTER_TYPE_MONSTER = 0
ENCOUNTER_TYPE_ANIMAL = 1
ENCOUNTER_TYPE_UNDEAD = 2
ENCOUNTER_TYPE_SWARM = 3

# Door status constants
DOOR_STATUS_SECRET = 0
DOOR_STATUS_TRAPPED = 1
DOOR_STATUS_LOCKED = 2
DOOR_STATUS_CLOSED = 3
DOOR_STATUS_OPEN = 4

# --- PROBABILITY CONSTANTS ---

# Door probabilities
DOOR_PROB_SECRET = 0.1
DOOR_PROB_TRAPPED = 0.1
DOOR_PROB_OPEN = 0.2
DOOR_PROB_LOCKED = 0.25

# Map Object probabilities
OBJECT_PROB_TRAP = 0.1
OBJECT_PROB_STATUE = 0.05
OBJECT_PROB_FOUNTAIN = 0.05
OBJECT_PROB_STAIRS_UP = 0.02
OBJECT_PROB_STAIRS_DOWN = 0.02
OBJECT_PROB_RUBBLE = 0.15
OBJECT_PROB_PILLAR = 0.1
OBJECT_PROB_ALTAR = 0.05
OBJECT_PROB_THRONE = 0.03
OBJECT_PROB_CHEST = 0.1
OBJECT_PROB_LEVER = 0.05
OBJECT_PROB_BUTTON = 0.05
OBJECT_PROB_CHAIR = 0.08
OBJECT_PROB_DEAD_BODY = 0.05
OBJECT_PROB_TABLE = 0.05
OBJECT_PROB_BED = 0.03
OBJECT_PROB_POOL = 0.02

# Item probabilities
ITEM_PROB_POTION = 0.2
ITEM_PROB_SCROLL = 0.2
ITEM_PROB_WEAPON = 0.15
ITEM_PROB_ARMOR = 0.15
ITEM_PROB_GOLD = 0.3

# Encounter probabilities
ENCOUNTER_PROB_MONSTER = 0.4
ENCOUNTER_PROB_ANIMAL = 0.2
ENCOUNTER_PROB_UNDEAD = 0.3
ENCOUNTER_PROB_SWARM = 0.1

# --- GLOBAL DECORATION PROBABILITY CONSTANTS ---

# For Rooms:
ROOM_OBJECT_CHANCE = 0.4
ROOM_ENCOUNTER_CHANCE = 0.2
ROOM_ITEM_CHANCE = 0.1

# For Hallways:
HALLWAY_ITEM_CHANCE = 0.05
HALLWAY_ENCOUNTER_CHANCE = 0.05

# For Walls:
WALL_DECORATION_CHANCE = 0.1
